version: '3.8'

services:
  focus-mariadb:
    image: ${REPOSITORY}focus-mariadb:${VERSION}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 30

  focus-reclamacao:
    image: ${REPOSITORY}focus-reclamacao:${VERSION}
    ports:
      - "80:8080"
    environment:
      - DB_FOCUS_URL=${DB_FOCUS_DEFAULT_URL}
    depends_on:
      focus-mariadb:
        condition: service_healthy

  focus-produto:
    image: ${REPOSITORY}focus-produto:${VERSION}
    ports:
      - "81:8080"
    environment:
      - DB_FOCUS_URL=${DB_FOCUS_DEFAULT_URL}
    depends_on:
      focus-mariadb:
        condition: service_healthy

  focus-pedido:
    image: ${REPOSITORY}focus-pedido:${VERSION}
    ports:
      - "82:8080"
    environment:
      - DB_FOCUS_URL=${DB_FOCUS_DEFAULT_URL}
    depends_on:
      focus-mariadb:
        condition: service_healthy

  focus-pagamento:
    image: ${REPOSITORY}focus-pagamento:${VERSION}
    ports:
      - "83:8080"
    environment:
      - DB_FOCUS_URL=${DB_FOCUS_DEFAULT_URL}
    depends_on:
      focus-mariadb:
        condition: service_healthy

  focus-cliente:
    image: ${REPOSITORY}focus-cliente:${VERSION}
    ports:
      - "84:8080"
    environment:
      - DB_FOCUS_URL=${DB_FOCUS_DEFAULT_URL}
    depends_on:
      focus-mariadb:
        condition: service_healthy

  focus-atendimento:
    image: ${REPOSITORY}focus-atendimento:${VERSION}
    ports:
      - "85:8080"
    environment:
      - DB_FOCUS_URL=${DB_FOCUS_DEFAULT_URL}
    depends_on:
      focus-mariadb:
        condition: service_healthy

  focus-security:
    image: ${REPOSITORY}focus-security:${VERSION}
    ports:
      - "86:8080"
    environment:
      - DB_FOCUS_URL=${DB_FOCUS_DEFAULT_URL}
    depends_on:
      focus-mariadb:
        condition: service_healthy

